language: java
jdk:
- oraclejdk8
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
- pip
- directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script: 
- ./svg-embed-font src/main/resources/BLACK_CHAOS.svg fonts/Lato-Heavy.ttf
- ./gradlew -iS build -x test
env:
  global:
    - secure: "kYf5wXWEbYIZcmFevn7uBgtV3XRf8GsexjkanIR/umRDtGQByX9ZaE3JQ26JXDG7LLuCBU9ruiMaZk9y6+zbvSInNYQpgdoBjWrEpSCBkqsAbsGpWyXayS6mZbYnB7t6qD+h18jM1QJG25hB+n/3rI4ZnN+4H2n0VuD5sI4fFVMvvoMjfyKv+p25ST0vMp6d0mXhn1CycQYCeIaQ2WpHba/kFO4b+EyjRzhuWkdxWiFW59Z1z5wEloELekxumQm3UoZc+L+xhnOxcHYKBrAaQPyjg08r1I5sN0wWPNQiXgKd5vash/vU8z/kaLGFk7su1rH+RnpPe17C8qQR7sky7jp01keb5wMx8a+WtwAsCLQLl9O+3rzexwyXIYUTVwR36ZU2vacJBbAu8wJr9OICw6gEKDGlolOo4rd2CCC++1nqYfoYmccW3ZwsWEBUq/QK+FPTTL5Rklb25nsTEMTeqRszIwFIycXdC2IiPBg7/uczymleVDActPENdsjh/6QToRDD2EklTyzC2qhNbJ0HU7yzd3mRxDnHqbOPcojuay+WsTGxErDKeLk0LifSf7UXQGY9nm5wHBCbBL6i5J4JbWvVpNVQtCa2rZZQ9QOONbAFRjTeYA+Qng8VutOZRmX+P1E3V7maI0cyr59VMEnCSk0zNS+w9dHzV4X9Vinywhk="
before_deploy:
- pip install --user awscli
deploy:
- provider: s3
  skip_cleanup: true
  region: eu-west-1
  bucket: devternity-code
  local_dir: build/distributions
  acl: public_read
after_deploy:
- aws lambda update-function-code --function-name devternity_card_generator --s3-bucket
  devternity-code --s3-key card-generator.zip
notifications:
  slack:
    secure: ZSh5SQZqQxI2JpAMkK6Uv0TreIyqQyNQWki5m6IRS8hHDwOD1WvDBSIwQor2hjyW7DTp61luvs6T/ON/vRyTBRfmpH71rwgBmtBih2PvVs0Xm+8+A1vwqlHuB/4zs5tgh6fo81RUth8fJJjd5txwdo7YLNZv3qXEw7wpkFHVPWgEIcOSKtabipKgei81ryqEAi8QeHFNhDJx+sUQtrreePj4G32l5k1f2Ua0IM8viPD87obhXDU1xPCPNZk1XliqZ5hgMHnnBcRi8L8SEP/WEgt//xuIHQ3IWY8qJlBwAqRK05uPSF/k10gtfugfheL50TxblfKMiJO2bi0uX7Yo+ZxMJsU1NA/xPJokKtukCi8PH0rPvgDhvRKLOYf89bhp2pxIs/CikoLcwWZFMgm6NeWfH1IfMQFkwk2Bj+OlWbqqnBZO/7mHJ1LUd0iVVFzG+AqKCHFwP23Wa16xEQK9XxyeFwHAnLx2YdmCIFUSTwrYB+yru57WLZa6ZhGY0tGC6alEi6UFuJGin2D/Q1ajdMR86gMRbqXvBYdkShtHa/NdLEM1+bTGWyE553xfVHzovc3P3QeEAiRR4je4V3PwqJrn7JoTcSMor7kUZrNRT+Rv7A1K8RFALe3VRObdlz0jFThoXrZyyVlPIRf4Eg9UrKGKpy16ednWk5UvSun0NTo=
